import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {
	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule
	} from '@angular/material';

import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    	MatAutocompleteModule,
	MatCommonModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
